default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: MANYO_EXAM_development

test:
  <<: *default
  database: MANYO_EXAM_test

production:
  <<: *default
  database: MANYO_EXAM_production
  username: MANYO_EXAM
  password: <%= ENV['MANYO_EXAM_DATABASE_PASSWORD'] %>
